# Generated by Django 4.1.2 on 2022-10-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
