# Generated by Django 4.1.2 on 2022-10-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0002_message_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
